# Generated by Django 4.1.7 on 2023-03-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('nid', models.CharField(blank=True, max_length=150, null=True)),
                ('college', models.CharField(max_length=250)),
                ('institute', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('hospital', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='media/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
