# Generated by Django 4.1.7 on 2023-03-14 14:44

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Anesthesiology', 'Anesthesiology'), ('Medicine', 'Medicine'), ('Neurology', 'Neurology'), ('Orthopaedics', 'Orthopaedics'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery')], default='Medicine', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='Male', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='graduate',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MD', 'MD'), ('Dr.MuD', 'Dr.MuD'), ('Dr.Med', 'Dr.Med'), ('DO', 'DO')], default='MD', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 20, 44, 36, 81955)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='undergraduate',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MBBS', 'MBBS'), ('BMBS', 'BMBS'), ('MBChB', 'MBChB'), ('MBBCh', 'MBBCh'), ('B.Med', 'B.Med'), ('MB', 'MB'), ('BM', 'BM'), ('B.S', 'B.S'), ('B.Surg', 'B.Surg')], default='MBBS', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='visit_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY'), ('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY')], default='Friday', max_length=150),
        ),
    ]
