# Generated by Django 4.1.7 on 2023-03-15 08:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0004_alter_doctor_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 14, 27, 59, 866629)),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nid', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='Male', max_length=150)),
                ('birth_date', models.DateField()),
                ('ssc', models.CharField(max_length=150)),
                ('hsc', models.CharField(max_length=150)),
                ('honor', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=250, null=True)),
                ('present_address', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='media/images')),
                ('join_date', models.DateTimeField(default=datetime.datetime(2023, 3, 15, 14, 27, 59, 866629))),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
