# Generated by Django 4.1.7 on 2023-03-17 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_doctor_department_alter_doctor_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 0, 3, 39, 170890)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 0, 3, 39, 170890)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 0, 3, 39, 170890)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 0, 3, 39, 170890)),
        ),
    ]
