# Generated by Django 4.1.7 on 2023-03-19 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_serial_age_alter_doctor_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 20, 46, 8, 977421)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 20, 46, 8, 979417)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 20, 46, 8, 979417)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 20, 46, 8, 978419)),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('before_breakfast', models.IntegerField(default=0)),
                ('morning', models.IntegerField(default=0)),
                ('before_lunch', models.IntegerField(default=0)),
                ('midday', models.IntegerField(default=0)),
                ('before_dinner', models.IntegerField(default=0)),
                ('night', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.serial')),
            ],
        ),
    ]
