# Generated by Django 4.1.7 on 2023-03-20 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_alter_doctor_join_date_alter_serial_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='pending_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='submit_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 0, 53, 7, 160236)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 0, 53, 7, 160236)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 0, 53, 7, 160236)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 0, 53, 7, 160236)),
        ),
    ]
