# Generated by Django 4.1.7 on 2023-03-21 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_serial_test_status_alter_doctor_join_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='test_status',
            new_name='test_done',
        ),
        migrations.AddField(
            model_name='serial',
            name='test_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serial',
            name='test_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 16, 55, 28, 239839)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 16, 55, 28, 243832)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 16, 55, 28, 243832)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 16, 55, 28, 239839)),
        ),
    ]
