# Generated by Django 4.1.7 on 2023-03-25 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0038_labtest_min_point_alter_doctor_join_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='patient',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 15, 33, 1, 531001)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 15, 33, 1, 531001)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 15, 33, 1, 531001)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 15, 33, 1, 531001)),
        ),
    ]
