# Generated by Django 4.1.7 on 2023-03-29 20:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0041_labtest_mix_point_alter_doctor_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 37, 22, 967869)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 37, 22, 967869)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 37, 22, 967869)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 37, 22, 967869)),
        ),
        migrations.CreateModel(
            name='LabAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nid', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='Male', max_length=150)),
                ('birth_date', models.DateField()),
                ('degree1', models.CharField(max_length=150)),
                ('degree2', models.CharField(blank=True, max_length=150, null=True)),
                ('degree3', models.CharField(blank=True, max_length=150, null=True)),
                ('institute1', models.CharField(blank=True, max_length=150, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=250, null=True)),
                ('present_address', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='media/images')),
                ('join_date', models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 37, 22, 967869))),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.lab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
