# Generated by Django 4.1.7 on 2023-03-29 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0042_alter_doctor_join_date_alter_serial_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labassistant',
            name='institute2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 52, 45, 468254)),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 52, 45, 491889)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 52, 45, 487899)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 52, 45, 487899)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 2, 52, 45, 485906)),
        ),
    ]
