# Generated by Django 4.1.7 on 2023-03-29 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_labassistant_institute3_alter_doctor_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='lab/images'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 3, 1, 30, 574302)),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 3, 1, 30, 581285)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 3, 1, 30, 577296)),
        ),
        migrations.AlterField(
            model_name='serial',
            name='visit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 3, 1, 30, 577296)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 3, 1, 30, 576296)),
        ),
    ]
